### PR TITLE
Dojo-Mini-MW-changes

### PR DESCRIPTION
**Pull request by SrikantManche**
@zeusbaba Please review the changes and approve

### CODE REVIEW

**Review by zeusbaba — APPROVED** [review]
well done @SrikantManche   
this is a good example of improving existing codebase

**Comment by zeusbaba** [comment]
i suggest we merge it right away so that the current iteration can be baselined  
@phamp890  @dhayanands how does it sound?

**Comment by zeusbaba** [comment]
> well done @SrikantManche
> this is a good example of improving existing codebase

one important feedback:  
branch name should reflect the work.  
this PR is not about the challenge anymore, as an example `improvements-on-existing-code` could be a better alternative here

**Comment by phamp890** [comment]
> i suggest we merge it right away so that the current iteration can be baselined @phamp890 @dhayanands how does it sound?

We like small PRs. Merge as soon as possible

**Pull request merged**
